### ISSUE TITLE
Unknown if this is an issue or not, but...

### ISSUE THREAD

**Issue by relvar99** [metstrike/meteor-oracle#5] opened 2016-02-07 03:00 UTC
I wanted to make sure you are aware of the possibility.  Some of our code executes a series of stored procedures, MERGEing rows into a few tables, and during what appears to be the OPLOG trailer, we see this in the logs 

I20160206-21:51:45.744(-5)? OPLOG: processed 100 records, lastProcessedId: 57008
I20160206-21:51:45.843(-5)? OPLOG: processed 100 records, lastProcessedId: 57108

I20160206-21:51:45.936(-5)? Exception in defer callback: TypeError: Cannot call method 'fetch' of null
I20160206-21:51:45.937(-5)?     at packages/mongo/oplog_observe_driver.js:509:1
I20160206-21:51:45.937(-5)?     at [object Object]._.extend.forEach (packages/id-map/packages/id-map.js:56:1)
I20160206-21:51:45.937(-5)?     at packages/mongo/oplog_observe_driver.js:507:1
I20160206-21:51:45.937(-5)?     at packages/mongo/oplog_observe_driver.js:16:1
I20160206-21:51:45.938(-5)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160206-21:51:45.938(-5)?     at packages/meteor/timers.js:6:1
I20160206-21:51:45.938(-5)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
I20160206-21:51:46.034(-5)? OPLOG: processed 100 records, lastProcessedId: 57208
I20160206-21:51:46.113(-5)? OPLOG: processed 100 records, lastProcessedId: 57308

If I get any additional information I will let you know.

-spencer

**Comment by metstrike** [comment] 2016-02-08 19:37
So far it looks like a bug, let us do more investigation.

**Comment by metstrike** [comment] 2016-02-08 21:04
Code that throws the exception: 

packages/mongo/oplog_observe_driver.js:509:1

```
  _fetchModifiedDocuments: function () {
    var self = this;
    Meteor._noYieldsAllowed(function () {
      self._registerPhaseChange(PHASE.FETCHING);
      // Defer, because nothing called from the oplog entry handler may yield,
      // but fetch() yields.
      Meteor.defer(finishIfNeedToPollQuery(function () {
        while (!self._stopped && !self._needToFetch.empty()) {
          if (self._phase === PHASE.QUERYING) {
            // While fetching, we decided to go into QUERYING mode, and then we
            // saw another oplog entry, so _needToFetch is not empty. But we
            // shouldn't fetch these documents until AFTER the query is done.
            break;
          }

          // Being in steady phase here would be surprising.
          if (self._phase !== PHASE.FETCHING)
            throw new Error("phase in fetchModifiedDocuments: " + self._phase);

          self._currentlyFetching = self._needToFetch;
          var thisGeneration = ++self._fetchGeneration;
          self._needToFetch = new LocalCollection._IdMap;
          var waiting = 0;
          var fut = new Future;
          // This loop is safe, because _currentlyFetching will not be updated
          // during this loop (in fact, it is never mutated).
          self._currentlyFetching.forEach(function (cacheKey, id) {
            waiting++;
            self._mongoHandle._docFetcher.fetch(  // <<<=== _docFetcher seems to be null here
              self._cursorDescription.collectionName, id, cacheKey,
```

**Comment by metstrike** [comment] 2016-02-08 21:09
@relvar99 How easy is this error to reproduce? When this happens, do you see any misbehavior on the client side / UI?

**Comment by relvar99** [comment] 2016-02-08 23:49
It happens consistently.  Our environment uses the 1.5.0 oracledb version, so that may be an issue.  When this happens, we do not observe any client/UI issues.

**Comment by metstrike** [comment] 2016-02-10 19:57
So far it looks like a possible bug in Meteor itself, maybe a racing condition between oplog_observe process and closing the connection? I can't imagine how else the _docFetcher property would become a null.

@relvar99 are you frequently opening and closing subscriptions in your application? That would make it possibility that a racing condition while closing connection would occur.

**Comment by relvar99** [comment] 2016-02-11 03:13
We are not explicitly opening and closing subscriptions, however, most if not all of our subscriptions are in an autoruns, and those subscription filters change based upon Session variables.

**Comment by relvar99** [comment] 2016-02-16 02:34
Spoke too soon,  it appears that maybe there are UI issues, but not sure if the error we are seeing is related to this issue or not.  Here is some additional information.  We are still investigating on our end ...

I20160215-21:22:20.043(-5)? Exception in defer callback: Error: The Mongo server and the Meteor query disagree on how many documents match your query. Maybe it is hitting a Mongo edge case? The query is: {"storyid":"AIP
SCENARIO1","_day":{"$gte":{"$date":1424235600000},"$lte":{"$date":1427169600000}}}
I20160215-21:22:20.044(-5)?     at Error (<anonymous>)
I20160215-21:22:20.046(-5)?     at packages/mongo/oplog_observe_driver.js:880:1
I20160215-21:22:20.047(-5)?     at Object.Meteor._noYieldsAllowed (packages/meteor/fiber_helpers.js:11:1)
I20160215-21:22:20.047(-5)?     at [object Object]._.extend._publishNewResults (packages/mongo/oplog_observe_driver.js:850:1)
I20160215-21:22:20.047(-5)?     at [object Object]._.extend._runQuery (packages/mongo/oplog_observe_driver.js:757:1)
I20160215-21:22:20.048(-5)?     at [object Object]._.extend._runInitialQuery (packages/mongo/oplog_observe_driver.js:658:1)
I20160215-21:22:20.048(-5)?     at packages/mongo/oplog_observe_driver.js:192:1
I20160215-21:22:20.048(-5)?     at packages/mongo/oplog_observe_driver.js:16:1
I20160215-21:22:20.049(-5)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160215-21:22:20.049(-5)?     at packages/meteor/timers.js:6:1

**Comment by metstrike** [comment] 2016-02-16 05:00
Oh well that doesn't look good, I have seen this error when the driver returned incorrect results for a query. This usually happened during experiments with nested structures as they are not fully supported yet.

The query in this case seems to be quite straightforward though. Please try to collect more detailed information if possible, you might also consider turning on the sqlDebug mode, which would print all actual sql queries sent to Oracle.

```
Oracle.setDefaultOracleOptions({strict: true});
```

**Comment by metstrike** [comment] 2016-02-16 22:29
Do you see the 2 errors happening at the same time? My feeling is that might be unrelated.

**Comment by metstrike** [comment] 2016-02-29 00:59
Couldn't collect more information about this issue, closing for now. Will reopen once we can reproduce or get more details.

**Closed as completed by metstrike** 2016-02-29 00:59 UTC
Labels: bug
